-- 프로토타입용 RLS 비활성화 (운영 전 반드시 정책 설정 필요)
ALTER TABLE artists          DISABLE ROW LEVEL SECURITY;
ALTER TABLE tracks           DISABLE ROW LEVEL SECURITY;
ALTER TABLE sample_packs     DISABLE ROW LEVEL SECURITY;
ALTER TABLE commission_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE collections      DISABLE ROW LEVEL SECURITY;
ALTER TABLE collection_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE commission_requests DISABLE ROW LEVEL SECURITY;
